### ISSUE TITLE
OkCoin code not functional after exchange upgrades to v3 version of the websocket

### ISSUE THREAD

**Issue by somguyth** [bitrich-info/xchange-stream#359] opened 2019-07-16 09:41 UTC
OkCoin/OkEx have updated their websocket to v3 and as of July 15th, the code here is not functional. Are there plans to update the code to the latest version of the websocket.

**Comment by dpisklov** [comment] 2019-10-04 10:41
this is a duplicate of #242

**Closed** 2019-10-04 12:43 UTC
